### ISSUE TITLE
PSR2 opinion on indentation of HTML

### ISSUE THREAD

**Issue by fulldecent** [php-fig/fig-standards#380]
Consider this code:

````
<?php
$x=[5, 6, 7];
?>
<html>
    <head>
        <title>Hi</title>
    </head>
    <body>
        <p>My favorite numbers are:</p>
        <ul>
<?php
foreach ($x as $number) {
?>
            <li><?= $x ?></li>
<?php
}
?>
        </ul>
    </body>
</html>
````

PRS2 gives an opinion that PHP code must be indented properly. However it is silent on the issue of `<?php` and `?>`. Could an opinion please be rendered on whether the above code is valid PRS2, specifically as to the indentation of the `<li>` line?

**Comment by glen-84** [comment]
Technically, it's valid, but as far as I know, PSR-2 is more concerned with files containing only PHP (classes, etc.). It is a PHP coding standard, so HTML indentation is unlikely to be covered.

That said, the rules that I like to follow personally, are:

1. Indent blocks that *do not* output anything, at the same level as the content that they wrap (in the case of control structures), or at the appropriate HTML indentation level (in the case of other PHP code).
2. Indent blocks that *do* output something, at the position where you would otherwise place nested HTML.
3. Use the alternative syntax (f.e. `if ():` ... `endif;`) for single line blocks that contain control structures.
4. Use `<?=` for output, and include the semi-colon (which is technically optional).

So, the code that you showed above would look like this:

```php
<?php
    $x = [5, 6, 7];
?>
<html>
    <head>
        <title>Hi</title>
    </head>
    <body>
        <p>My favorite numbers are:</p>
        <ul>
            <?php foreach ($x as $number): ?>
            <li><?= $x; ?></li>
            <?php endforeach; ?>
        </ul>
    </body>
</html>
```

Another example (with indented output, etc.):

```php
<p>
    <?= $x; ?>
</p>
<p>
    <?php
        $x = 1;
        $y = 2;
    ?>
    <span><?= ($x + $y); ?></span>
</p>
```

**Comment by samdark** [comment]
Not going to cover it in PSR-12.
