### ISSUE TITLE
[PSR-7] HTTP message interfaces

### ISSUE THREAD

**Issue by designermonkey** [php-fig/fig-standards#394]
Would it be easier to understand if the interfaces were called simply

```
ClientRequestInterface
ClientResponseInterface
ServerRequestInterface
ServerResponseInterface
```

It's confusing to try and figure out which is which without reading the information first.

**Comment by weierophinney** [comment]
While I like the idea, per other discussions on the mailing list, I'll be reverting to the original interfaces (message, request, response, incoming). I may rename the `IncomingRequestInterface` to `ServerRequestInterface`, however, per your suggestion.

**Comment by designermonkey** [comment]
But what do they mean? What's the context for each? An interface set should be easy to understand the context by just looking at the name.

**Comment by weierophinney** [comment]
@designermonkey The new/old interfaces are now just message, request, response, and server request. I think they're self-describing at this point.

**Comment by designermonkey** [comment]
What does message mean though?

I'm not trying to be funny, honestly. In apps I've used and written, a `Request` is what comes into my app and a `Response` is what I send out, but I understand that there would need to be those for when my app makes a `Request` and `Response` outwardly (as a client). Just having request and response is a little too abstract IMO.

Ah, is message the `ServerResponse`?

Is there any way this can be put to a vote?

**Comment by weierophinney** [comment]
@designermonkey Request and Response are used whether you are handling a request (server side) or making one (client side); both are messages, and thus descend from that common interface. The "ServerRequest" exists because we want to abstract some common concerns of server-side applications that technically fall outside the definition of a standard HTTP message, such as input sources. All of this information is in the meta document, along with links to relevant specifications and documents.

No, we are not going to put the naming to a vote. The terminology stems from the HTTP specifications, and is in common usage in PHP frameworks, the language itself, and across other languages.

**Comment by weierophinney** [comment]
@mvrhov Then aliasing is your friend. The point is that the names are fully qualified, and if you're having naming collisions or autoloading problems, those problems are in your code and can be resolved without changes to the spec.

**Comment by mvrhov** [comment]
The reason I'm mentioning this here is because this would prevent WTFs to other facing similar problems I have and they wouldn't need to alias because of that.

**Comment by mvrhov** [comment]
Sorry for bringing this up. @weierophinney: It seems that really is a problem php/php-src#1149

**Comment by weierophinney** [comment]
@mvrhov My point remains the same: you can either alias or import the namespace in order to avoid that problem until the patch is accepted. This is a good idea regardless, to make it clear the difference between your own definitions and those imported from elsewhere.
