### ISSUE TITLE
PSR-7 and HTTP/2

### ISSUE THREAD

**Issue by Faryshta** [php-fig/fig-standards#436]
http://thenextweb.com/insider/2015/02/18/http2-first-major-update-http-sixteen-years-finalized/

The new revision of http is on its way. Does the PSR-7 has that in mind or a form of support/testing/consideration about the subject?

Specially the differences between versions 1.1 and 2 http://http2.github.io/faq/#what-are-the-key-differences-to-http1x

Maybe at this point PHP itself is not ready to implement HTTP/2 and it will be good to discuss other options or implementations

**Comment by weierophinney** [comment]
The primary changes in HTTP/2 are around transmission of messages, not the messages themselves. As such, the objects provided in PSR-7 will continue to be semantically correct for HTTP/2.

**Comment by newcron** [comment]
@weierophinney  @pmjones  I think you're not aware of all changes in HTTP/2. 

The two most notable differences are about persistent connections and push messages (server sends http entities that were not requested by the client). Looking at PSR-7 I don't see, how that is reflected in the standard?

**Comment by simensen** [comment]
@newcron As I understand it nothing has changed w/ the messages themselves. I believe that is what @weierophinney was getting at when he said that HTTP/2 was only changing the transport of the messages but not changing the messages themselves.

Yes, there are persistent connections and yes there are push messages, but requests are still made using the same message format over persistent connections and push messages are also delivered using the same message format.

Said another way, if PSR-7 has issues and is incompatible with HTTP/2 then I'd think that PHP itself would be incompatible with HTTP/2. PHP isn't going to be doing anything different for HTTP/2 than it already does but it works just fine behind a HTTP/2 server like nginx. I'm already doing this on a few sites. I think you were alluding to this yourself when you mentioned that maybe PHP itself wasn't ready for this. I think you are right. Now, a React PHP server, or another async PHP server....

If you have specific information on what you think is broken/wrong w/ PSR-7 I think it would be useful to discuss those points. I think it would be particularly helpful if you could describe which parts of PSR-7 are in conflict w/ the two things you've mentioned and how you think PSR-7 could be altered to make it work better w/ those two things.

---

I only have a basic understanding about how something like server push would work, but this is what I'm thinking would happen:

```
send_http2_response(Response::asHtmlString('<h1>Hello World</ha><script src="/data.json'));
push_http2_response('/data.json', Response::asJson(json_encode(['username' => 'beau'])));
```

... in both cases, we'd be creating/dealing with PSR-7 responses. However, something else would be in charge of multiplexing the streams and ensuring that the client gets the /data.json response by way of a server push instead of requiring the browser to request it on its own.
