### ISSUE TITLE
[PSR-2 - 4.4. Method Arguments] One line per argument seems exagerated 

### ISSUE THREAD

**Issue by AntonioCS** [php-fig/fig-standards#464]
Why MUST we have one line per argument? I try to keep my code under the 80 column limit and most of the times I can do stuff like this
    
```
public function mergeCurrentListItemWithsetWeekData(
            array $arrayWithListItemsFromData, $user, &$setweekdata) {
```

But now according to the standard I will have to do this:

```
public function mergeCurrentListItemWithsetWeekData(
            array $arrayWithListItemsFromData, 
            $user, 
            &$setweekdata
) {
```

Why do I need those 3 extra lines?

**Comment by MacDada** [comment]
It is an accepted standard, isn't it too late to post objections?

**Comment by samdark** [comment]
It could be a thing to fix in subsequent one so nope, let it be.

**Comment by MacDada** [comment]
If so, then I'm against ;p

Right now it is consistent, it makes code readable and if one has too many arguments (or too long) – then it's a code design problem, not a code style convention problem.

Don't like the idea of splitting arguments into lines? Find a way to make your method simpler. It probably doesn't have to (and shouldn't) be so complicated.

Plus why change something that ppl already use and would waste time on changing? What's the gain? So that everybody has more flexibility in setting up their coding style? I don't care how exactly it looks, only that it looks the same everywhere.

:-1:

**Comment by Coreinsanity** [comment]
@MacDada Personally I think it's kind of ironic that you say you don't care how it looks, when a coding standard is both to ensure readability AND standardize coding styles.

I think one per line is a little ridiculous, especially when you get to things like closures and use statements. Even in their example with just three vars and three args:

```
$longArgs_longVars = function (
    $longArgument,
    $longerArgument,
    $muchLongerArgument
) use (
    $longVar1,
    $longerVar2,
    $muchLongerVar3
) {
   // body
};
```

just looks excessive where as

```
$longArgs_longVars = function (
    $longArgument, $longerArgument, $muchLongerArgument
) use (
    $longVar1, $longerVar2, $muchLongerVar3
) {
   // body
};
```

looks much less excessive. Compact, but readable.

You don't need a lot of arguments for it to get tediously long (horizontally). In the case of that example closure, the arguments look fine on their own line but look bad on one line because of length, and especially bad if you include the use vars on the same line:

```
$longArgs_longVars = function ($longArgument, $longerArgument, $muchLongerArgument) use ($longVar1, $longerVar2, $muchLongerVar3) {
   // body
};
```

That's 131 chars wide, without that many arguments or vars.


All that being said, should they change it on the grounds of it already being an accepted standard, and in wide use? That could be up for debate, but just because you allow multiple vars/arguments per line, doesn't mean all the people have to change. It could be either or, with maybe a max number of argument/vars per line (eg: In the case above, a fourth argument would look kind of stupid on that line).

Though I agree, in general, that your methods and such shouldn't be taking in excess numbers of arguments unless you absolutely need it. It sounds like that particular method may be doing too much of the work and it should be spread out.

**Comment by MacDada** [comment]
@Coreinsanity 

> Personally I think it's kind of ironic that you say you don't care how it looks

I do care. I like symmetry. I like clean, well-named, organised code. Of all other programmers I've been working with, I was always the one who gave this topic the biggest attention.

But… I've changed my coding style a few times. I still do in smaller matters from time to time. That's because we all learn what's easier to read, what makes more sense, etc.

But most of all, we all learn what's the common accepted way of styling code and **this** is the most important factor as it comes to readability. In the end it doesn't matter if you put a brace in the same line as function declaration or in a new line. If it's the same way everywhere, your mind will parse that subconsciously and fast.

That's my point. We can argue if new argument in every line is better or not, but in the end we should just keep it one way.

----

As for many long arguments, etc – redesign your code. Having 3 arguments and 3 use statements, that is 6 passed in variables, it's an obvious bad way of doing things. Single Responsibility Principle? Testing and debugging nightmare. Please, don't argue how to style bad design – give your effort in making the design better instead.

**Comment by Coreinsanity** [comment]
@MacDada 

Ah, my apologies, you said in your previous post you didn't care how it looks, only about the other half (standardized look).

I took the example given in the specs very own documentation. I've never written a statement with that many things going into it. Personally, I think sticking that much in a closure is ridiculous in itself (Who wants that just in the middle of a bunch of code?)

I'm not interested in styling bad design. For me, personally, I find two lines easier to read than three or more (including the function/closure declaration). But it's not just about how many arguments you have, it's about their names. If you have a constructor with type hinting and two or three arguments, that could also be kind of long depending on the verbosity of the class names. At that point, it's an issue if readability for me - it might fit nicely on two lines (method dec and then the arguments) but just be a little too long for comfort on one line. Granted, I've never hit this use, but yeah.

You're looking at this at kind of a small view point, just because a method or function declaration is long doesn't mean it has a crap-ton of needless arguments.

But, I agree, keeping a standard is good. Changing it past it's finalization is kind of counter-productive.

**Comment by michaelcullum** [comment]
The spec is finalised but should you believe this is a typo/formatting issue or worthy of errata, please post it to the mailing list.
