### ISSUE TITLE
[PSR-7] Simplifying Header interface

### ISSUE THREAD

**Issue by ahundiak** [php-fig/fig-standards#489]
**Being able to add multiple headers in one operation is what motivated this gist.**

**Replace**
`public function  getHeaders();`
`public function  hasHeader     ($name);`
`public function  getHeader     ($name);`
`public function  getHeaderLines($name);`
**With**
`public function  getHeader($name,$defaultValue=null,$lines=false);`
**Where**
`if ($name === null) return all headers` *replaces getHeaders()*
`if ($name === string)`
`..AND header exists`
`....if $lines === false return comma delimited string`
`....if $lines === true  return array of values` *replaces getHeaderLines()*
`..OR  header does not exist`
`....return default value` *replaces hasHeader()*
`if ($name === array)`
`..return array of headers values - because we can`

**Replace**
`public function withHeader     ($name, $value);`
`public function withAddedHeader($name, $value);`
**With**
`public function withHeader     ($name, $value, $line=false);`
**Where**
`if ($name === string and $value === null)`
`..*** remove the header, ` *currently missing withoutHeader()*
`if ($name === string)`
`..add the header or header lines based on $line flag` *replaces withAddedHeader()*
`if ($name === array)`
`..` *set one* **or more** *headers*

The ability to set multiple headers without individual cloning will help to alleviate performance concerns.

Reducing the number of methods from 6 to 2 (even at the slight cost of increasing their complexity)
will enhance the chances of the standard being widely used.

**Comment by milesj** [comment]
I disagree as this breaks single responsibility and separation of concerns. Multi-purpose methods are a no no.

**Comment by ahundiak** [comment]
The single responsibility of the proposed getHeader method is to return 0 or more headers.  I fail to see how that would cause any alarms.  The existing getHeader method already return 0 or 1 headers.  By rights it should toss an invalid argument exception thus forcing user to always use hasHeader before getHeader.  Do we really want to go down that road?

The proposed asLines argument merely indicates the representation of a header line.  If there is a SRP violation here then it is at the class level.  To be pure, getHeader should return a Header class object and we should use some other means to extract a particular representation.  Again, do we really want to do that?

The single responsibility for the proposed withHeader method is to add 0 or more headers.  Quantity and representation again seems irrelevant.  Would you object to having withHeaders and withAddedHeaders methods?

If you object to using a null value to remove a header then quite a bit of the spec will have to be redone.  Consider withScheme which states that "An empty scheme is equivalent to removing the scheme".  Is it really a problem to say that an empty header is equivalent to removing the header?  Do we really need to add a withoutHeader method?  Do we really want a spec that does not offer a standard means of removing a header?

**Comment by weierophinney** [comment]
@ahundiak We deliberately chose *not* to have methods for setting headers en masse. The rationale was due to confusion over whether such methods would *overwrite* or *merge*. The language for describing one or the other is very easy to misinterpret, and we found that if we did provide adequate language describing one style of operation, then another group of developers were asking for additional methods for the other behavior, which further complicates the interface.

As such, we chose the methods we currently have, which operate on single header values. `withHeader()` always creates or overwrites; `withAddedHeader()` always creates or merges.

**Comment by weierophinney** [comment]
@ahundiak Also, we chose specifically to return `null` from `getHeader()` if the header does not exist, rather than having a `$default` argument. The reason is that with PHP 5.4 and above, you can accomplish the same using:

```php
$value = $message->getHeader('X-Foo') ?: 'default value';
```

By omitting the argument, we simplify the interface, which simplifies implementation; additionally, the described signatures are designed to work with PHP operators such as the above.

**Comment by weierophinney** [comment]
@pmjones and/or @simensen — please close.
