### ISSUE TITLE
[PSR-7] ServerRequestInterface:: getFileParams() makes it impossible to be used without SAPI?

### ISSUE THREAD

**Issue by m00t** [php-fig/fig-standards#501]
I am researching the possibility to use PSR-7 interfaces with a PHP-written webserver (react-php in particular, but not limited by it) without any SAPI like php-fpm or mod_apache. And seems like this is very hard to create some kind of general solution for that.
* You can not use move_uploaded_file() without SAPI. When you have $_FILES like structure returned by this method, every client will use this function, because it will works fine in their php-fpm environment. And this code will not be able to be moved from php-fpm. So this is kinda leaky abstraction in my opinion: clients will use implementation of $_FILES in PHP SAPI instead of using this interface. 
* Even when we are not using move_uploaded_file() in client, we have another problem. For example, again, we create php webserver in something like react-php. And client uploading a 2Gb file in multipart/form-data to this application. This is a stream. And I can, for example, pipe it to amazon s3 directly as soon as I receive a chunk of it. But I can not, because I have to create $_FILES-like structure. That means I should save this file to disk, and then read it from disk (or load it completely to memory?) in order to upload it to amazon s3.
* SAPI-less webserver is not the only variant where PSR-7 can help unless it have getFileParams() method. Another option is something like browserkit driver. Look at the http-foundation's UploadedFile: it has "testing" parameter. This is because http-foudation's interfaces are leaky the same way the PSR-7 will be leaky about files. But http-foundation is not interface, it is implementation, so it can address these leaks by such hacks. There is no way to address it when you have an interface unless there will written something like "client implementation MUST NOT rely on move_uploaded_file()" which seems a bit ugly for me.

The solution for my opinion at the first look is to introduce some kind of UploadedFileInterface abstraction, which can be SAPI-agnostic and provide both move() and streaming possibilities.

**Comment by m00t** [comment]
The https://github.com/php-fig/fig-standards/pull/498 introduces UploadedFileInterface in a way that actually conflicts with this issue, and makes it impossible to use without SAPI because of 
> More precisely, the implementation MUST ensure that is_uploaded_file() returns true for the path

And this will be true only for SAPI. Browserkit driver, for example, will not be able to exist with such kind of interface.

**Comment by weierophinney** [comment]
@m00t Considering #498 has not yet been merged, it would have been simpler to put this feedback directly on the PR; right now, we're having to track multiple locations.

My assertion is: the abstractions already work for the scenarios you describe.

`getFileParams()`, and most of the various additional methods defined in `ServerRequestInterface`, exist to provide convenience abstractions to the various superglobals, plain and simple. As you correctly note, most of the superglobals are only properly populated by the underlying SAPI. However, most of them can *also* be derived from other sources:

- query parameters can be derived from the URI's query string.
- cookie parameters can be derived from the `Cookie` headers.
- body parameters can be derived by parsing the message body (and, in fact, that's the recommendation when receiving a non-POST and/or non-`application/x-www-form-urlencoded` message).

Technically, file parameters can *also* be derived by parsing the message body.

In fact, you *must* do this if you're using an HTTP request method other than `POST` *currently* in PHP. (I've done exactly this in [zfcampus/zf-content-negotiation](https://github.com/zfcampus/zf-content-negotiation), because we needed to be able to deal with file uploads coming via `PATCH` and `PUT`).

You can accomplish it relatively quickly via stream operations; read a line at a time, looking for MIME boundaries and parsing the headers for each section. This can even be done without caching the contents of the stream in-memory… except that as soon as we start reading the stream, it **is** in memory. And that, I think, is your primary contention.

One possible solution is to do similarly to PHP: parse the files to essentially a `php://temp` stream, or write them to a specified temporary upload directory.  (This is exactly what we do in zf-content-negotiation.) In other words, as you are parsing for the file metadata, you're also pushing the files to the filesystem (or memory, in the case of `php://temp`), allowing developers to interact with the metadata in the fashion to which they are accustomed.

Of course, it means that `is_uploaded_file()` and `move_uploaded_file()` *can* *not* work, and any solution around manipulating the uploaded files (e.g., moving them to another directory) needs to consider that. Again, however, it *can* be accomplished; as noted with zf-content-negotiation, we've made it work already.

The other solution is, in these circumstances, to process the message body directly, instead of interacting with the file parameters. In the situation you presented in your second bullet-point, streaming an incoming file directly to S3, honestly, that's *exactly* how I would approach it. I wouldn't use `$_FILES` at all. Why? For exactly the reasons you indicate. I can take the incoming message body, *which is a stream*, and process it in place, piping individual parts directly to a stream that's sending to S3.

It looks like your main contention is this language in the proposal:

> More precisely, the implementation MUST ensure that is_uploaded_file() returns true for the path

I'll update the proposal to remove that.

My main point in this is: use `getFileParams()` and/or `getUploadFiles()` where they make sense, and drop to the message body stream when they don't.  Additionally, I and others have already proved that you can create the same structure as `$_FILES` by parsing the incoming message body directly, in a performant manner, and have the results work seamlessly with operations that would normally work directly on `$_FILES`, and without relying on the built-in `*_uploaded_file()` functions. As such, I assert that the currently proposed abstractions will work fine for the scenarios you outline.

**Comment by m00t** [comment]
@weierophinney with your last changes, this issue no more related to https://github.com/php-fig/fig-standards/pull/498. But there is still an issue with $_FILES abstraction in my opinion, and you did not get my main concern. I need some time to think how to explain it more carefully and clearly. Also I will take a look at zf-content-negotiation.

**Comment by m00t** [comment]
@weierophinney you are right, I will close this ticker in favor of https://github.com/php-fig/fig-standards/pull/498, and will write all my thoughts there. This will be much more simple and understandable.
