### ISSUE TITLE
[PSR-7] Header Line Interface

### ISSUE THREAD

**Issue by wolfy-j** [php-fig/fig-standards#502]
Remembering long discussion about complex header values such as cookies, cache and etc. It feels that representing header line as object seems pretty reasonable and flexible:

```php
return $reponse->withAddedHeader(
        'Set-Cookie', 
        new Cookie('name', 'value', 3600)
    );
```

Where `Cookie` class should only contain valid `__toString` method. Same statement can be found in meta document:
> So long as the object has functionality for casting the value to a string, these objects can be used to populate the headers of an HTTP message.

Is it reasonable to create additional interface `HeaderLineInterface` or `HeaderInterface` used to identify such classes? Even if it contains only one method:

```php
interface HeaderLineInterface
{
    /**
     * Get string representation of header line.
     *
     * @return string
     */
    public function __toString();
}
```

**Comment by weierophinney** [comment]
:-1:

Specifying a `__toString()` method as the sole interface method is pointless, and complicates creating simple headers (e.g., `$message->withAddedHeader('X-Foo-Bar', new GenericHeader('Baz'))`). Additionally, there's nothing saying you cannot already do this anyways:

```php
$message->withAddedHeader('X-Foo-Bar', (string) $someHeadeObject);
```

In ZF2, we went the route of each header being an object. What we found was:

- For simple headers, it complicated usage.
- For complex headers, it's often nice, as you could specify behavior (e.g., `$accept->match($contentType)`).
- Most of the time, you end up using a convenience method we created, `$headers->addHeaderLine($name, $value)`, because it's *simpler*.

When we started creating Apigility, one thing we found is that a lot of people are developing compact, targeted libraries around header values:

```php
$contentTypes = (new Accept($message->getHeader('accept')))->parse();
```

This is nice, because it moves the abstraction *out* of the message, and creates a domain-specific library/class around it.

This does not preclude having dedicated classes for representing a header. To the contrary: we expect that with some complex values, such as `Cache-Control`, `Set-Cookie`, and whatnot, we'll see dedicated classes arise that make it easy to specify the values you want, and the class can then take care of serialization. However, that does *not* need to be part of the specification. Instead, you use the class to serialize the value so you can pass it to the message:

```php
$message->withAddedHeader('Cache-Control', $cacheControl->serialize());

// or
$message->withAddedHeader('Cache-Control', (string) $cacheControl);
```

This keeps the specification lean, and reduces implementation cost.

**Comment by weierophinney** [comment]
@pmjones and/or @simensen — Please close.
