### ISSUE TITLE
The wording on ServerRequestInterface::getParsedBody is misleading

### ISSUE THREAD

**Issue by mnpenner** [php-fig/fig-standards#506]
`ServerRequestInterface::getParsedBody` says:

> If the request Content-Type is either application/x-www-form-urlencoded or multipart/form-data, and the request method is POST, this method MUST return the contents of $_POST.

Assuming the Content-Type is "application/x-www-form-urlencoded" and the request method is POST, but the "parsed body" was overwritten via `withParsedBody`, then this method shouldn't actually return `$_POST`, should it?

**Comment by Tobion** [comment]
I guess this just means the "default" behavior unless it has explicitly been overwritten. But should indeed be clarified.

**Comment by mnpenner** [comment]
Yeah, that's what I assumed, but it does say "MUST". I think the paragraph should be amended slightly:

> If the request Content-Type is either application/x-www-form-urlencoded or multipart/form-data, and the request method is POST, this method MUST return the contents of $_POST unless the parsed body is overwritten such as via `withParsedBody`.

Or it can just be removed removed entirely as the comment on `withParsedBody` already covers it:

> If the request Content-Type is either application/x-www-form-urlencoded or multipart/form-data, and the request method is POST, use this method ONLY to inject the contents of $_POST.

And really, `getParsedBody` should just return whatever is set via `withParsedBody` I think, there doesn't need to be any special logic in it.

**Comment by webmozart** [comment]
I agree with @mnpenner. I think this issue is closely related with #515.

**Comment by m00t** [comment]
@webmozart @mnpenner I disagree with
> If the request Content-Type is either application/x-www-form-urlencoded or multipart/form-data, and the request method is POST, use this method ONLY to inject the contents of $_POST.

I think the $_POST body parsing is a very common thing and closely related to `ServerRequestInterface` so interface implementation could use $_POST (or parse message body in non-SAPI environments) to populate `parsedBody` by itself without forcing client to do it himself.

Maybe the problem actually is that we try to merge cases when body parsing is an implementation task (when dealing with application/x-www-form-urlencoded or multipart/form-data POST request) with cases when body parsing is an interface client task (when client uses something like `withParsedBody(json_decode(...))`)?

**Comment by mnpenner** [comment]
Maybe change the wording on `withParsedBody` to say that it *SHOULD* use $_POST if those conditions are met. i.e., it's more of an implementation hint, but as long as you're doing something sensible with the body, that's fine.

Also, I'm not quite sure -- does `withBody` have an affect on `getParsedBody`? i.e., should it be parsing whatever the body is currently set to? If "no", then there's no way for developers to set the body to some raw multipart/form-data and get back the parsed content, is there?

**Comment by weierophinney** [comment]
> does withBody have an affect on getParsedBody

@mnpenner — I've deliberately *not* tied `withBody()` to parsed body parameters, mainly because I'm not convinced it's necessary. I cannot think of a single situation where I'd want to swap the incoming message body (which is what `ServerRequestInterface` contains) with something else, making the point moot. If it *is* done, it's a _caveat emptor_ situation. (In other words, I think this falls in the realm of extreme edge case.)

**Comment by weierophinney** [comment]
> Assuming the Content-Type is "application/x-www-form-urlencoded" and the request method is POST, but the "parsed body" was overwritten via withParsedBody, then this method shouldn't actually return $_POST, should it?

@mnpenner — First, a clarification: the spec says that it returns the _contents_ of `$_POST`, not `$_POST` itself (i.e., it's not a reference). Now, the question is: how do the contents of `$_POST` get into the object in the first place? Most likely via either the constructor, or `withParsedBody()`. We don't define constructors in the interfaces, so the second is a safe assumption.

The language is as it is to set an expectation for consumers: they can expect that if the request meets the specified conditions, calling `getParsedBody()` will behave exactly the same as if they were using `$_POST`. This helps developers not familiar with using request implementations become comfortable with using PSR-7: "How do I access `$_POST['foo']`? Oh, I see, via `$request->getParsedBody()['foo']`. That's kinda verbose, but OK." Since this is also the most common use case (as browsers only support GET and POST for form submissions from HTML forms unless you're using XHR), it makes sense to stipulate this connection.

I'm not opposed to saying SHOULD, but the language MUST removes ambiguity from the most common use case.

**Comment by michaelcullum** [comment]
The spec is finalised but should you believe this is a typo/formatting issue or worthy of errata, please post it to the mailing list.
