### ISSUE TITLE
"Final" in final class names

### ISSUE THREAD

**Issue by jeserkin** [php-fig/fig-standards#525]
I've seen this document [002-psr-naming-conventions.md](https://github.com/php-fig/fig-standards/blob/master/bylaws/002-psr-naming-conventions.md), but there is no mentioning of final classes. Seems it would be more readable as well if `final class Something` would also be named `SomethingFinal`

**Comment by GrahamCampbell** [comment]
> would also be named SomethingFinal

I really don't like that idea.

**Comment by GrahamCampbell** [comment]
Also, why would you stick it on the end anyway, given that for abstracts, it goes at the start?

**Comment by jeserkin** [comment]
Okay. I agree. A the end it doesn't struck like some part of the OOP, rather something entirely else. But my proposal was more regarding, that it could/should be present in naming convention as well. i.e. `FinalCoreEvents`

**Comment by GrahamCampbell** [comment]
I think the naming convention should be to omit "Final" from the class name.

**Comment by jeserkin** [comment]
Why? Abstract should be used according to doc, but final should be omitteed?

**Comment by simensen** [comment]
@jeserkin Some would argue that Abstract* and *Interface are inappropriate as well. The bylaw doesn't say anything at all about how to handle final so I'd guess we are free to do whatever we want the first time it comes up and/or address this *at that point in time*. Since providing final classes is already controversial enough, and since we try to avoid producing concrete implementations, I don't know that the question of `final` will ever actually come up for FIG.

**Comment by jeserkin** [comment]
I see. Well, I for one use it as constant container. Like if you have system/app and it has some i.e. events, that are not customisable, but a necessary measure, so that app would be readable. Java has enums and so on, but PHP doesn't, at least yet. So I think, that `final` class is a pretty good place for that.

```php
final class EventsDesc {
  const EVENT_ONE;

  const EVENT_TWO;
}

//...

$EventDispatcher->dispatch(EventsDesc::EVENT_ONE, new Event());
```

Anyways. It is clear, that for now, it woun't be present in standard so one can do how ever one wants regarding that.

**Comment by mnpenner** [comment]
`Abstract` and `Interface` is at least useful because there's usually an accompanying concrete implementation without the qualifier. "Final" classes don't need companions.

**Comment by GrahamCampbell** [comment]
> "Final" classes don't need companions.

I agree.

**Comment by guilhermeblanco** [comment]
I was a firm -1 voter of Abstract*, *Trait and *Interface.
Now if we really consider any data type (trait, interface) or class modifier (abstract) part of the name, we should then enforce to have Final*, follow the same rule, or should we make an exception for every rule?

**Comment by jeserkin** [comment]
> "Final" classes don't need companions.

I agree partially. Companion isn't needed, but all in all, all of those standards are taken for comfort of the development process, so the question is, would it be easier/more readable if the final keyword would be present in class/file name - yes.

i.e. Exception. Probably most of the people have custom Exception classes. Something like RequestNotDispatchableException. Would it be easier to work with this file just from listing if the Exception part was missing from the name? I don't think so.

**Comment by mnpenner** [comment]
> would it be easier/more readable if the `final` keyword would be present in class/file name

I don't believe so. The only time "final" comes into play is when you try to extend the class and discover you can't.

"Abstract", "Interface" and "Exception" are useful during every day usage. For example, "Abstract" and "Interface" let you know that the class is not instantiable -- you know right away that you want to typehint your functions against the interface, instantiate the concrete class, and ignore the abstract classes. "Exception" classes are throwable, everything else isn't. What about "Final" classes? They're no different than concrete classes in terms of usage.

**Comment by krzysiekpiasecki** [comment]
Keyword final does not constitute interface and therefore should not be articulated in class name.

**Comment by frankbardon** [comment]
I tend to agree with @mnpenner. Finding yourself in a situation where you need to extend a class marked `final` SHOULD mean one of two things:

1. The original code has a flaw, and the library maintainer(s) should be notified.
2. You are doing something you should not and should re-think your actions.

-1

**Comment by spiritix** [comment]
> Now if we really consider any data type (trait, interface) or class modifier (abstract) part of the name, we should then enforce to have Final*, follow the same rule, or should we make an exception for every rule?

+1. We should at least be consistent.

**Comment by donquixote** [comment]
-1

We add the "Abstract*" and "*Interface" not because they have these modifier keywords, but because these elements play a specific role in a library. The role of a "final" class, however, is typically just "concrete implementation", which does not make them very different from regular classes.

On the other hand, an "*Util" suffix would make sense for classes with only static members, even if they don't have a dedicated modifier keyword. These classes do have a special role.

In Drupal, the "Abstract" classes are suffixed with "*Base" instead of prefixed with "Abstract*". Again this shows that it is not so much about the modifier keyword, but about describing the role of the element.

Personally, I already regard every concrete implementation as "inheritance discouraged". The clean way, in my book, is to only inherit from abstract classes, and use composition otherwise.
In some cases I still do inherit from non-abstract classes out of lazyness/convenience.. but it would not be a huge leap if I would put the "final" modifier on all concrete implementations by default.

This is why I don't think "Final" should be part of the class name.

**Comment by michaelcullum** [comment]
PSR-2/1 are final but PSR-12 is still under discussion. If you wish to suggest it's inclusion please post to the mailing list.
