### ISSUE TITLE
phpDoc variable, attribute, param possible value suggestion

### ISSUE THREAD

**Issue by gcds** [php-fig/fig-standards#529]
Hello,

I would like to suggest to make possible values list for @param, @property and etc phpDoc tags it would really help on autocompleting in normal IDE like PHPStorm. Kinda like this:

```
@param ["Type"] [name] [possible values] [<description>]
```

Example What I imagine:

```php
/**
 * @param string $type (img,article,link) Element type
 */
public function getElement($type);
```

Real life example is PHPStorm Symfony2 Plugin which suggest possible values for container, route, doctrine repositories, entities and other thing by tagging function param with special tag.

**Comment by Coreinsanity** [comment]
I think this would be useful.

I think this could also be expanded upon to allow the argument signature of a closure to be exposed for those implementing it to know:

```
/**
 * @param array $array The array to walk
 * @param Closure $callback ($key, $value) The callback will be called and passed each key and respective value.
 */
public function walkArray($array, Closure $callback)
```

**Comment by frankbardon** [comment]
I'd argue that the description can be, and is used for that purpose in current cases; and does a decent job. I find it more interesting in the second example by @Coreinsanity. There isn't really any way to capture anonymous function signatures in PHPDoc to my knowledge... and if you're supporting the second, there's no reason to not support the first.

**Comment by jacobsantos** [comment]
I think this should really be the domain of `@typedef`. Unfortunately, I don't think the array syntax is as flexible to allow something like this.

```php
/**
 * @typedef MySet enum {
 *     @type string "img"
 *     @type string "article"
 *     @type string "link"
 * }
 * @param MySet $type Element type
 */
```

Regardless of the final product, I think reusing `@typedef` should be used for more solutions. You want to keep it simple, yes?

**Comment by Coreinsanity** [comment]
Honestly without more explanation, your @typedef example seems more confusing. Can you elaborate any? I also don't see how you could apply it to closure signatures, though technically that was my addition to the suggestion not the OPs.

**Comment by jacobsantos** [comment]
@Coreinsanity 

```php
/**
 * @typedef MyClosure \Closure {
 *     This is the summary for MyClosure function.
 *
 *     @param mixed $something Give something.
 *     @return mixed Return value.
 * }
 * @param MyClosure $callback
 */
public function walkArray($array, \Closure $callback)
```

It is also possible to have the definition inline with the `@param`. I rather like using `@typedef` since using Go more.

**Comment by Coreinsanity** [comment]
@jacobsantos 
Ah, that makes much more sense to me now, thank you!

Yeah, after that example I prefer the typedef suggestion for closures and their signature, as this gives us the option to not only outline things like the signature of a closure, but also define the closure's purpose and what the arguments of it do, their type, and the closure's return in a way that an IDE autocomplete and doc generator could take advantage of.

I think where I got mixed up was your use of enum, as the OP was referring to possible (example) values you can provide, where as an enum is a specific set of variables it has to fall within (such as a ConnectionState enum that can only have Open and Closed values)

As far as enums go: When you use something like C# + VisualStudio intellisense, because it has the actual enum type it knows the only possible values when showing you autocomplete options for that argument. So given

```csharp

enum ConnectionState 
{
    Open,
    Closed
}

// And a method somewhere
public void SetConnectionState(ConnectionState newState)
```

It knows that the only possible autocomplete options for newState are ConnectionState.Open or ConnectionState.Closed.

Given that in PHP the best you can get to an enum (as far as I know) is something like:

```php
abstract class ConnectionState
{
    const Closed = 0;
    const Open   = 1;
}

/*usage: */ ConnectionState::Closed
```

Then I think the best way to represent this would be a tag somehow defining the class as an enum class in PHPdoc, which feels hacky to me seeing as it's not an actual language construct:

```php
/**
 * @enum
 */
abstract class ConnectionState
{
   // Const parameters
}
```

Naturally I think if we want to be able to specify things as enums so doc generators and autocomplete can read it, it would be best to somehow have that specified at the source: The actual "enum" definition/class, this would reduce repetition and keep the definition centralized in that one spot. For example, I would hate to have to inherit or copy that typedef to each spot that uses an enum-like argument. I think the same goes with the OPs suggestion, though, as far as enums play in (Copying or inheriting the possible values for an enum argument, each place it's used, would get tedious.)

**Comment by jacobsantos** [comment]
@Coreinsanity I think that example is a reason I like `@typedef` usage.

I did see the possibility that perhaps OP was wanting Enum type support. The other objection I have is that I don't like the inclusion of additional syntax in that way.

I think the idea is a good one. The issue I have had with proposals and the current spec is that it has been hard to specify possible values. I don't think anyone has really put forth a good idea on how to solve that.

One thing of note is the possibility that the tags might be moving to this style instead.

```php
/**
 * @param $something : string Description
 * @param $[name] [: "Type"] [<description>]
 */
```

Although, technically, it isn't something that would be necessary, given that it should be simple enough to parse with `$` to separate type and parameter name.

**Comment by jacobsantos** [comment]
You might be better off going here: https://github.com/phpDocumentor/fig-standards where the standard is actually being worked on.

**Comment by M1ke** [comment]
This might not be the appropriate place to ask, but has something of this form (specifying allowed string values to create a "pseudo-enum" been implemented anywhere? I am trying to work comments of this format into code to allow phpstorm to signal correct variable input to a function and an implementation of this issue would do the job

**Comment by M1ke** [comment]
As an adendum there seems to be a similar discussion on the phpDocumentor repository https://github.com/phpDocumentor/phpDocumentor2/issues/557

**Comment by michaelcullum** [comment]
Please use the mailing list to discuss this further.
