### ISSUE TITLE
[PSR-12] Declare construct

### ISSUE THREAD

**Issue by glen-84** [php-fig/fig-standards#654]
1) Doesn't it make more sense for the equals sign to be spaced like other operators?

```php
declare(strict_types = 1);
```

2) Has "There MUST not be a blank line before the strict types declaration." been voted on?

I think it's cleaner/clearer to leave a blank line:

```php
<?php

declare(strict_types = 1);

namespace Vendor\Package;

use X;
use Y;
```

**Comment by samdark** [comment]
1) Personally I agree but there are counter arguments such as the way it's used in PHP manual.
2) I don't think it was voted on (check mailing list just in case). I think it looks better w/o extra blank line.

**Comment by GrahamCampbell** [comment]
What about putting it on the same line as `<?php` so that `namespace` can go in the same place it would have otherwise been on php 5.

**Comment by GrahamCampbell** [comment]
```php
<?php declare(strict_types = 1);

namespace Vendor\Package;

use X;
use Y;
```

**Comment by GrahamCampbell** [comment]
Or is that invalid syntax?

**Comment by juliangut** [comment]
2) what about file docblocks? It really makes it clearer to have that blank line between docblock and declare strict

```php
<php
/**
 * @author me
 * @package any
 * ...
 */

declare(strict_types = 1);

namespace MyNamespace;

class MyClass
{

}

```

**Comment by samdark** [comment]
@GrahamCampbell looks OK to me.

**Comment by samdark** [comment]
2) Is it valid syntax?

**Comment by glen-84** [comment]
> 1) Personally I agree but there are counter arguments such as the way it's used in PHP manual.

I would be very surprised if all samples in the PHP manual were valid PSR-2, so I don't think that this is a very strong counter-argument.

If you use a linting tool with a rule to ensure space before/after assignment, this would have to be an exception, which seems both unnecessary and inconsistent.

> 2) I don't think it was voted on (check mailing list just in case). I think it looks better w/o extra blank line.

Could you vote on it? I'm not a member so I can't start a vote, but I am very interested to hear what the consensus is. The same question applies to the namespace declaration, assuming that there is no declare construct above it.

**Comment by GrahamCampbell** [comment]
> 2) Is it valid PHP syntax to have anything between declare and open tag?

The RFC would suggest that it is invalid syntax to have anything other than whitespace between it and the opening tag. Not sure if comments are allowed before, but I'd assume phpdoc is not allowed before.

That comes to another point I guess. Often people want file headers before the namespace, so that would look pretty if the declair was on the same line as the `<?php` too.

**Comment by glen-84** [comment]
Here are the voting options, should you decide to open it for voting:

##### Declare construct operator (equals sign) spacing

a) No spaces before/after
b) One space before and after
c) Other (please specify)

##### Declare construct position

a) No blank line above.
b) One blank line above.
c) Same line as <?php
d) Other (please specify)

**Comment by glen-84** [comment]
> Not sure if comments are allowed before, but I'd assume phpdoc is not allowed before.

It is allowed.

**Comment by danemacmillan** [comment]
The section regarding `declare` usage should have its wording addressed. It is not clear. See https://github.com/php-fig/fig-standards/issues/655 for an explanation.

**Comment by quantumpacket** [comment]
@GrahamCampbell Doesn't PHP allow usage of multiple declare statements? We have 3 directives that can be used afaik (ticks, encoding, strict_types). That being the case, a file could have multiple statements. Having it on the same line as the opening tag would not work. I think it should have a space before and after so that the statements can be grouped.

> 2) Is it valid PHP syntax to have anything between declare and open tag?

@samdark Yes, and no. If using the file level declare for `strict_types` it must be the first statement, which does not disallow comments. I'm not sure if the other directives have such a rule when it comes to file level declare. However, declare can be used anywhere afaik since it can be declared at a block level.

Something to note from the manual:
> Caution: When combined with namespaces, the only legal syntax for declare is declare(encoding='...'); where ... is the encoding value. declare(encoding='...') {} will result in a parse error when combined with namespaces.

**Comment by mbadolato** [comment]
> 1) Doesn't it make more sense for the equals sign to be spaced like other operators?

Any by that same token, should there be a space between ```declare``` and the opening parenthesis?

```php
declare (strict_types = 1);
```
The [PHP Manual](http://php.net/manual/en/control-structures.declare.php) shows it with a space in the very 1st usage after the opening paragraph, though other examples throughout the page show no space.  

> If you use a linting tool with a rule to ensure space before/after operators, this would have to be an exception, which seems both unnecessary and inconsistent.

Just ran an extremely quick and dirty test to see what happens when php-cs-fixer hits the declare statement when enforcing psr2 standards. It adds the space before the parens, does not add around the ```=```. Granted this is unscientific and php-cs-fixer is not the authority, was just curious to how it would behave currently.

```php-cs-fixer --dry-run --verbose --diff --level=psr2 fix test.php```
```
F
Legend: ?-unknown, I-invalid file syntax, file ignored, .-no changes, F-fixed, E-error
   1) /Users/mbadolato/development/projects/phpvalueobjects/common/test.php (braces)
      ---------- begin diff ----------
      --- Original
      +++ New
      @@ @@
       <?php
      -declare(strict_types=1);
      +declare (strict_types=1);


      ---------- end diff ----------
```

**Comment by RyanThompson** [comment]
I think the declare statement SHOULD have a blank line above it as well. Anywhere there is a reasonable potential to have a block of code (in this case / at this time only two lines but a block none the less) you SHOULD consider blank lines as appropriate according to previous PSRs.

Even if there is NOT multiple declarations, it STILL shouldn't be smacked up against a piece of syntax that is not related. Keep non-related syntax separated. In general helps consuming the code (tasty code) I think.

```
<?php
declare(ticks=1);
declare(encoding='ISO-8859-1');

/// Moar code 
```

Much cleaner to present the code like this:

```
<?php

declare(ticks=1);
declare(encoding='ISO-8859-1');

/// Moar code - breathe easy.
```

**Comment by glen-84** [comment]
> Any by that same token, should there be a space between declare and the opening parenthesis?

I see it as a method invocation, which wouldn't have a space before the opening parenthesis – what are you grouping it with? A function declaration?

**Comment by mbadolato** [comment]
> what are you grouping it with? A function declaration?

For the php-cs-fixer test? No the entire test.php file was simply

```php
<?php

declare(strict_types = 1);
```

Running it on a full class exhibits the same behavior

**Comment by glen-84** [comment]
@mbadolato What I meant was, what do you see it as being similar to?

**Comment by schinkel** [comment]
I agree with @glen-84 on the spacing issue; consistency is more important to me. I also think you should not use the php manual as a reference for the coding standard. Once a standard is finalized it is easy enough to update the code examples in the manual.

Just my two cents :)

**Comment by mbadolato** [comment]
@glen-84 Oh hah, sorry... it was 1am when I responded :smile: I agree with you; I see it more as method invocation as well. I was just posing the question. Syntax highlighting in PhpStorm seems to consider it a keyword construct (like for, while, etc) but to me it does look like a method invoke.

I do, however, definitely think the space should be around the equals sign, and there should be a blank line after ```<?php```.  Personally, I've been putting it below file header info:

```php
<?php

/**
 * Fantabulous file of magic stuff
 */

declare(strict_types = 1);

namespace My\Stuff;

use More\Great\Things;

class Foo {
    // ...
}
```

**Comment by michaelcullum** [comment]
This discussion should be taking place on the mailing list, please continue it there if you wish.

Thanks
